function z0 = computeIC(D1_theta,R,gamma,theta)
%COMPUTEIC
%    Z0 = COMPUTEIC(D1_THETA,R,GAMMA,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    11-Nov-2017 21:49:32

t2 = gamma.^2;
t3 = t2+1.0;
t4 = 1.0./sqrt(t3);
z0 = [R.*gamma.*t4;R.*t4;theta;-D1_theta.*R.*t4;D1_theta.*R.*gamma.*t4;D1_theta];
