function [Ek,Ep] = energy_con(D1_x,D1_y,D1_theta,I,M,d,g,theta,y)
%ENERGY_CON
%    [EK,EP] = ENERGY_CON(D1_X,D1_Y,D1_THETA,I,M,D,G,THETA,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    08-Nov-2017 12:44:01

t2 = D1_y+D1_theta.*d.*cos(theta);
t4 = sin(theta);
t3 = D1_x-D1_theta.*d.*t4;
Ek = D1_theta.^2.*I.*(1.0./2.0)+M.*(t2.^2+t3.^2).*(1.0./2.0);
if nargout > 1
    Ep = M.*g.*(y+d.*t4);
end
